apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: GOTRUE_API_HOST
              value: 0.0.0.0
            - name: GOTRUE_API_PORT
              value: "9999"
            - name: GOTRUE_DB_DATABASE_URL
              value: postgres://postgres:@db:5432/postgres?search_path=auth
            - name: GOTRUE_DB_DRIVER
              value: postgres
            - name: GOTRUE_DISABLE_SIGNUP
            - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
            - name: GOTRUE_EXTERNAL_PHONE_ENABLED
            - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
              value: authenticated
            - name: GOTRUE_JWT_EXP
            - name: GOTRUE_JWT_SECRET
            - name: GOTRUE_MAILER_AUTOCONFIRM
            - name: GOTRUE_MAILER_URLPATHS_CONFIRMATION
              value: /auth/v1/verify
            - name: GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE
              value: /auth/v1/verify
            - name: GOTRUE_MAILER_URLPATHS_INVITE
              value: /auth/v1/verify
            - name: GOTRUE_MAILER_URLPATHS_RECOVERY
              value: /auth/v1/verify
            - name: GOTRUE_SITE_URL
            - name: GOTRUE_SMS_AUTOCONFIRM
            - name: GOTRUE_SMTP_ADMIN_EMAIL
            - name: GOTRUE_SMTP_HOST
            - name: GOTRUE_SMTP_PASS
            - name: GOTRUE_SMTP_PORT
            - name: GOTRUE_SMTP_SENDER_NAME
            - name: GOTRUE_SMTP_USER
            - name: GOTRUE_URI_ALLOW_LIST
          image: supabase/gotrue:v2.2.12
          name: supabase-auth
          resources: {}
      restartPolicy: Always
status: {}
