apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kong
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kong
    spec:
      containers:
        - env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /var/lib/kong/kong.yml
            - name: KONG_DNS_ORDER
              value: LAST,A,CNAME
            - name: KONG_PLUGINS
              value: request-transformer,cors,key-auth,acl
          image: kong:2.1
          name: supabase-kong
          ports:
            - containerPort: 8000
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/kong/kong.yml
              name: kong-claim0
      restartPolicy: Always
      volumes:
        - name: kong-claim0
          persistentVolumeClaim:
            claimName: kong-claim0
status: {}
