apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: studio
  name: studio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: studio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: studio
    spec:
      containers:
        - env:
            - name: STUDIO_PG_META_URL
              value: http://meta:8080
            - name: SUPABASE_ANON_KEY
            - name: SUPABASE_SERVICE_KEY
            - name: SUPABASE_URL
              value: http://kong:8000
          image: supabase/studio:latest
          name: supabase-studio
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
